name: Build test matrix images

on:
  push:
    paths:
      - 'smoke-tests/matrix/**'
      - '.github/workflows/build-test-matrix.yaml'
    branches: 'main'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: burrunan/gradle-cache-action@v1.8
        with:
          job-id: matrix-smoke

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          TAG="$(date '+%Y%m%d').$GITHUB_RUN_ID"
          echo "Using extra tag $TAG"
          ./gradlew buildMatrix pushMatrix -PextraTag=$TAG
        working-directory: smoke-tests/matrix