name: Build test matrix images

on:
  push:
    paths:
      - 'smoke-tests/matrix/**'
      - '.github/workflows/build-test-matrix.yaml'
    branches: ['main']
  workflow_dispatch:

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: burrunan/gradle-cache-action@v1.10
        with:
          job-id: matrix-smoke

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          TAG="$(date '+%Y%m%d').$GITHUB_RUN_ID"
          echo "Using extra tag $TAG"
          ./gradlew buildLinuxTestImages pushMatrix -PextraTag=$TAG
        working-directory: smoke-tests/matrix

  buildWindows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true

      - uses: actions/checkout@v2

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: burrunan/gradle-cache-action@v1.10
        with:
          job-id: matrix-smoke

      - name: Login to GitHub Package Registry
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          TAG="$(date '+%Y%m%d').$GITHUB_RUN_ID"
          echo "Using extra tag $TAG"
          ./gradlew buildWindowsTestImages pushMatrix -PextraTag=$TAG
        working-directory: smoke-tests/matrix